from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from backend.config import settings

class SendGridClient:
    def __init__(self):
        self.api_key = settings.SENDGRID_API_KEY
        self.sender_email = settings.SENDGRID_SENDER_EMAIL

    def send_officer_email(self, to_email: str, officer_name: str, brief_details: dict, custom_subject: str = None, custom_body: str = None) -> bool:
        """
        Sends an email briefing to a municipal officer regarding a detected risk cluster.
        """
        if not self.api_key or not self.sender_email:
            print("SendGrid configuration missing.")
            return False

        if custom_body:
            # Wrap BriefAgent's generated message in clean styling
            html_content = f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px;">
                <h2 style="color: #ef4444; margin-top: 0;">⚠️ CivicMind Risk Escalation Alert</h2>
                <p>Dear <strong>{officer_name}</strong>,</p>
                <div style="white-space: pre-line; color: #4b5563; line-height: 1.6; background-color: #f9fafb; padding: 15px; border-radius: 6px; margin: 15px 0;">
                    {custom_body}
                </div>
                <div style="margin: 25px 0 15px; text-align: center;">
                    <a href="http://localhost:3000/officer" style="background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
                        Review & Dispatch Work Order
                    </a>
                </div>
                <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 20px 0;">
                <p style="font-size: 11px; color: #9ca3af; text-align: center; margin-bottom: 0;">
                    This is an automated operational alert generated by CivicMind Autonomous City Agent.
                </p>
            </div>
            """
        else:
            # Build clean HTML content summarizing the risk brief
            html_content = f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px;">
                <h2 style="color: #ef4444; margin-top: 0;">⚠️ CivicMind Risk Escalation Alert</h2>
                <p>Dear <strong>{officer_name}</strong>,</p>
                <p>The CivicMind Urban Intelligence system has detected and aggregated an active infrastructure failure risk requiring your review.</p>
                
                <div style="background-color: #f9fafb; padding: 15px; border-radius: 6px; margin: 15px 0;">
                    <p style="margin: 5px 0;"><strong>Risk Severity:</strong> <span style="color: #ef4444; font-weight: bold;">{brief_details.get('risk_level', 'HIGH')}</span></p>
                    <p style="margin: 5px 0;"><strong>Confidence:</strong> {int(brief_details.get('confidence', 0.7) * 100)}%</p>
                    <p style="margin: 5px 0;"><strong>Estimated Affected Residents:</strong> {brief_details.get('affected_residents', 2400)}</p>
                    <p style="margin: 5px 0;"><strong>Causal Chain:</strong> {brief_details.get('causal_hypothesis', 'Multiple correlated failure signals.')}</p>
                </div>
                
                <p><strong>Causal Reasoning:</strong></p>
                <blockquote style="border-left: 4px solid #3b82f6; padding-left: 15px; margin: 15px 0; color: #4b5563; font-style: italic;">
                    "{brief_details.get('causal_hypothesis', 'Awaiting deep forensics verification.')}"
                </blockquote>
                
                <div style="margin: 25px 0 15px; text-align: center;">
                    <a href="http://localhost:3000/officer" style="background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
                        Review & Dispatch Work Order
                    </a>
                </div>
                
                <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 20px 0;">
                <p style="font-size: 11px; color: #9ca3af; text-align: center; margin-bottom: 0;">
                    This is an automated operational alert generated by CivicMind Autonomous City Agent.
                </p>
            </div>
            """

        subject = custom_subject if custom_subject else f"[CivicMind Alert] CRITICAL Infrastructure Failure Threat in {brief_details.get('zone_id', 'Your Ward')}"

        message = Mail(
            from_email=self.sender_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_content
        )

        try:
            sg = SendGridAPIClient(self.api_key)
            response = sg.send(message)
            return response.status_code in [200, 201, 202]
        except Exception as e:
            print(f"Failed to send email via SendGrid: {str(e)}")
            return False
