/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as MapRouteImport } from './routes/map'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AutopsyRouteImport } from './routes/autopsy'
import { Route as IndexRouteImport } from './routes/index'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopsyRoute = AutopsyRouteImport.update({
  id: '/autopsy',
  path: '/autopsy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autopsy': typeof AutopsyRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/map': typeof MapRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autopsy': typeof AutopsyRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/map': typeof MapRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autopsy': typeof AutopsyRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/map': typeof MapRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/autopsy' | '/citizen' | '/command' | '/map' | '/transparency'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autopsy' | '/citizen' | '/command' | '/map' | '/transparency'
  id:
    | '__root__'
    | '/'
    | '/autopsy'
    | '/citizen'
    | '/command'
    | '/map'
    | '/transparency'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutopsyRoute: typeof AutopsyRoute
  CitizenRoute: typeof CitizenRoute
  CommandRoute: typeof CommandRoute
  MapRoute: typeof MapRoute
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopsy': {
      id: '/autopsy'
      path: '/autopsy'
      fullPath: '/autopsy'
      preLoaderRoute: typeof AutopsyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutopsyRoute: AutopsyRoute,
  CitizenRoute: CitizenRoute,
  CommandRoute: CommandRoute,
  MapRoute: MapRoute,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
